const places = [{
  place_id: 0,
  place_name: 'โกเบ Steak And Cheesy Bar',
  place_total_rating: 4.6,
  place_district_name: 'ราชเทวี, กรุงเทพ',
  place_picture: 'https://www.iam-tour.com/new/wp-content/uploads/2016/12/kobe-beef4.jpg',
  place_lat: 13.7547483,
  place_long: 100.5249892,
  place_address: '77/6 ม. 3 บางไป้ อำเภอเมือง นนทบุรี 11000',
  place_about: 'เป็นร้านสเต็กสไตล์ญี่ปุ่น ทานง่าย มีเมนูหลากหลายราคาตามคุณภาพเนื้อที่เราสั่ง แต่ส่วนตัวคิดว่ามาทานเมนูง่ายๆ ไม่แพงก็คุ้มมากเลยค่ะ เพราะได้ทั้งน้ำซุป ข้าว เครื่องดื่ม ผลไม้ คืออิ่มเลยม้วนเดียวจบ',
  place_contact_info: '090-6866563',
  place_type: 'restaurant',
  place_price_range: [100, 500],
  place_rewards_id: null,
  place_rewards_points: 15,
  place_suggestions: ['ปลาโอโทโร่', 'แก้มปลาฮามาจิต้มซีอิ้ว', 'ซาชิมิรวม', 'ปลาดุกฟู'],
  place_operate_time: '12.30 - 13.00 จ.-ศ.',
  place_district: 'ราชเทวี',
  place_province: 'กรุงเทพ',
  place_reviews: [{
    review_id: 0,
    place_id: 0,
    review_title: '~::<<รีวิวแบบเมพๆ>>::~ Honmono : The ‘REAL’ Sushi By Iron Chef',
    review_author_name: 'Jabzz Eater',
    review_site_name: 'Pantip.com',
    review_site_url: 'https://www.pantip.com',
  }, {
    review_id: 1,
    place_id: 0,
    review_title: 'รายการ เอิทกับดรีม ชวนไปแดก วันนี้ขอเสนอ :: KUY RESTAURANT ::',
    review_author_name: 'Earth & Dream',
    review_site_name: 'Google.com',
    review_site_url: 'https://www.pantip.com',
  }],
}, {
  place_id: 1,
  place_name: 'Waterside Sushi Restaurant',
  place_total_rating: 4.3,
  place_district_name: 'วัฒนา, กรุงเทพ',
  place_picture: 'https://media-cdn.tripadvisor.com/media/photo-s/04/bd/c0/05/waterside-restaurant.jpg',
  place_lat: 13.82905,
  place_long: 100.631732,
  place_address: '77/6 ม. 3 บางไป้ อำเภอเมือง นนทบุรี 11000',
  place_about: 'เป็นร้านสเต็กสไตล์ญี่ปุ่น ทานง่าย มีเมนูหลากหลายราคาตามคุณภาพเนื้อที่เราสั่ง แต่ส่วนตัวคิดว่ามาทานเมนูง่ายๆ ไม่แพงก็คุ้มมากเลยค่ะ เพราะได้ทั้งน้ำซุป ข้าว เครื่องดื่ม ผลไม้ คืออิ่มเลยม้วนเดียวจบ',
  place_contact_info: '090-6866563',
  place_type: 'restaurant',
  place_price_range: [200, 400],
  place_rewards_id: null,
  place_rewards_points: null,
  place_suggestions: null,
  place_operate_time: '12.30 - 13.00 จ.-ศ.',
  place_district: 'ราชเทวี',
  place_province: 'กรุงเทพ',
  place_reviews: [{
    review_id: 0,
    place_id: 0,
    review_title: '~::<<รีวิวแบบเมพๆ>>::~ Honmono : The ‘REAL’ Sushi By Iron Chef',
    review_author_name: 'Jabzz Eater',
    review_site_name: 'Pantip.com',
    review_site_url: 'https://www.pantip.com',
  }, {
    review_id: 1,
    place_id: 0,
    review_title: 'รายการ เอิทกับดรีม ชวนไปแดก วันนี้ขอเสนอ :: KUY RESTAURANT ::',
    review_author_name: 'Earth & Dream',
    review_site_name: 'Google.com',
    review_site_url: 'https://www.pantip.com',
  }],
}, {
  place_id: 2,
  place_name: 'Waterside Sushi Restaurant',
  place_total_rating: 4.3,
  place_district_name: 'วัฒนา, กรุงเทพ',
  place_picture: 'https://media-cdn.tripadvisor.com/media/photo-s/04/bd/c0/05/waterside-restaurant.jpg',
  place_lat: 13.82905,
  place_long: 100.631732,
  place_address: '77/6 ม. 3 บางไป้ อำเภอเมือง นนทบุรี 11000',
  place_about: 'เป็นร้านสเต็กสไตล์ญี่ปุ่น ทานง่าย มีเมนูหลากหลายราคาตามคุณภาพเนื้อที่เราสั่ง แต่ส่วนตัวคิดว่ามาทานเมนูง่ายๆ ไม่แพงก็คุ้มมากเลยค่ะ เพราะได้ทั้งน้ำซุป ข้าว เครื่องดื่ม ผลไม้ คืออิ่มเลยม้วนเดียวจบ',
  place_contact_info: '090-6866563',
  place_type: 'restaurant',
  place_price_range: [200, 400],
  place_rewards_id: null,
  place_rewards_points: null,
  place_suggestions: null,
  place_operate_time: '12.30 - 13.00 จ.-ศ.',
  place_district: 'ราชเทวี',
  place_province: 'กรุงเทพ',
  place_reviews: [{
    review_id: 0,
    place_id: 0,
    review_title: '~::<<รีวิวแบบเมพๆ>>::~ Honmono : The ‘REAL’ Sushi By Iron Chef',
    review_author_name: 'Jabzz Eater',
    review_site_name: 'Pantip.com',
    review_site_url: 'https://www.pantip.com',
  }, {
    review_id: 1,
    place_id: 0,
    review_title: 'รายการ เอิทกับดรีม ชวนไปแดก วันนี้ขอเสนอ :: KUY RESTAURANT ::',
    review_author_name: 'Earth & Dream',
    review_site_name: 'Google.com',
    review_site_url: 'https://www.pantip.com',
  }],
}];

const challenges = [{
  challenge_id: 0,
  challenge_name: 'ทริป 1 วันสุดมัน ในเยาวราชสำหรับคนกรุงเทพ',
  challenge_picture: 'https://static.independent.co.uk/s3fs-public/styles/article_small/public/thumbnails/image/2014/10/09/14/bangkok_getty.jpg',
  challenge_rewards_id: null,
  challenge_rewards_points: 15,
  challenge_goal_type: 'goto_all_places',
  challenge_goal_caption: 'ไปเที่ยวให้ครับ 3 ที่นี้ภายใน 1 วัน',
  challenge_places: places,
  challenge_start_data: new Date(),
  challenge_end_date: (new Date()).setDate((new Date()).getDate() + 7),
  challenge_total_rating: 0,
  challenge_location_label: 'เยาวราช, กรุงเทพ',
}, {
  challenge_id: 1,
  challenge_name: 'ภารกิจท่องเที่ยวทะเลใน 7 วัน',
  challenge_picture: 'https://www.goway.com/media/uploads/asia/images/thailand/general_thailand/thai_boats_on_beach_islandparadise_island_in_thailand_1_hero.jpg',
  challenge_rewards_id: null,
  challenge_rewards_points: 20,
  challenge_goal_type: 'goto_all_places',
  challenge_goal_caption: 'ไปเที่ยวให้ครบ 3 ที่นี้ภายใน 7 วัน',
  challenge_places: places,
  challenge_start_data: new Date(),
  challenge_end_date: (new Date()).setDate((new Date()).getDate() + 7),
  challenge_total_rating: 4.7,
  challenge_location_label: 'ทะเลอ่าวไทย, ภาคใต้',
}, {
  challenge_id: 2,
  challenge_name: 'ทัวร์เชียงใหม่ 3 ที่ใน 1 วัน ทำได้รึเปล่า?!',
  challenge_picture: 'https://wm.thaibuffer.com/o/u/pirawan/travel3/Doi%20Suthep6.jpg',
  challenge_rewards_id: null,
  challenge_rewards_points: 10,
  challenge_goal_type: 'goto_all_places',
  challenge_goal_caption: 'ไปเที่ยวให้ครับ 3 ที่นี้ภายใน 1 วัน',
  challenge_places: places,
  challenge_start_data: new Date(),
  challenge_end_date: (new Date()).setDate((new Date()).getDate() + 7),
  challenge_total_rating: 5,
  challenge_location_label: 'เชียงใหม่',
}];

const sections = [{
  id: 0,
  title: 'อาหาร',
  challenges: [challenges[0], challenges[1]],
}, {
  id: 1,
  title: 'สถานที่ท่องเที่ยว',
  challenges: [challenges[2], challenges[0]],
}, {
  id: 2,
  title: 'กิจกรรม',
  challenges: [challenges[1], challenges[2]],
}];

export const challengeForHomePage = {
  spotlight: [challenges[2], challenges[0], challenges[1]],
  food: [challenges[1], challenges[0]],
  activity: [challenges[2], challenges[1]],
  place: [challenges[0], challenges[2]],
};

export const allChallenges = challenges;
export const getAllPlaces = places;
export const getSections = () => sections;

export const getChallengeById = id => challenges[id];
export const getPlaceById = id => places[id];
